import type {
  ConfirmationSource,
  ExpenseStatus,
  FundingKind,
  PaymentStatus,
  SubmissionDisplayState,
} from "./budgetClient";

/** Budget Stage 3: every Budget UI string (see CLAUDE.md "No hardcoded UI text"). */
export const BUDGET_TEXT = {
  moduleTitle: "ניהול תקציב",
  nav: {
    planning: "תקציב ותכנון",
    expenses: "הוצאות",
    suppliers: "ספקים",
    settings: "הגדרות",
    switchToElectionDay: "מעבר ליום הבחירות",
    switchToBudget: "מעבר לניהול תקציב",
  },
  guard: {
    unavailableTitle: "המודול אינו זמין",
    unavailableHint: "ניהול התקציב אינו פעיל עבור מערכת זו.",
    forbiddenTitle: "אין לך הרשאה לצפות בדף זה",
    forbiddenHint: "פנו לבעל המערכת לקבלת הרשאה לניהול התקציב.",
  },
  common: {
    save: "שמירה",
    cancel: "ביטול",
    add: "הוספה",
    edit: "עריכה",
    close: "סגירה",
    retry: "נסו שוב",
    loadError: "לא ניתן לטעון את הנתונים",
    reason: "סיבה",
    reasonRequired: "יש לציין סיבה",
    amount: "סכום (₪)",
    amountInvalid: "סכום לא תקין",
    date: "תאריך",
    notes: "הערות",
    active: "פעיל",
    inactive: "לא פעיל",
    activate: "הפעלה",
    deactivate: "השבתה",
    delete: "מחיקה",
    none: "—",
    search: "חיפוש",
    all: "הכל",
    history: "היסטוריה",
    noHistory: "אין עדיין שינויים",
    saved: "נשמר",
  },
  kinds: {
    party: "מימון מפלגתי",
    donation: "תרומות",
    personal: "אישי",
  } satisfies Record<FundingKind, string>,
  payer: { party: "המפלגה", campaign: "הקמפיין" },
  expenseStatus: {
    draft: "טיוטה",
    committed: "התחייבות",
    incurred: "בוצע",
    closed: "סגור",
    cancelled: "בוטל",
  } satisfies Record<ExpenseStatus, string>,
  paymentStatus: {
    unpaid: "לא שולם",
    partial: "שולם חלקית",
    paid: "שולם במלואו",
  } satisfies Record<PaymentStatus, string>,
  submissionState: {
    awaiting_preapproval: "ממתין לאישור תקציבי מוקדם",
    preapproved: "אושר תקציבית מראש",
    collecting_documents: "איסוף מסמכים",
    ready: "מוכן להגשה",
    sent: "נשלח למממן",
    returned: "הוחזר לתיקון",
    reference_received: "התקבל אישור/אסמכתת תשלום",
  } satisfies Record<SubmissionDisplayState, string>,
  confirmationSource: {
    funder_notice: "הודעת המממן",
    supplier_confirmation: "אישור הספק",
    bank_transfer: "העברה בנקאית",
    other: "אחר",
  } satisfies Record<ConfirmationSource, string>,
  planning: {
    title: "תקציב ותכנון",
    subtitle: "מקורות מימון, תכנון לפי קטגוריה והיסטוריית שינויים",
    totalBudget: "סה\"כ תקציב",
    planned: "מתוכנן בקטגוריות",
    unallocated: "לא הוקצה לקטגוריות",
    usage: "בהתחייבות + בביצוע",
    sources: "מקורות מימון",
    newSource: "מקור מימון חדש",
    sourceName: "שם המקור",
    sourceKind: "סוג מימון",
    originalAmount: "סכום מקורי",
    currentAmount: "סכום נוכחי",
    adjustments: "התאמות",
    remaining: "יתרה",
    adjust: "עדכון סכום",
    adjustHint: "סכום חיובי להגדלה, שלילי להקטנה",
    categories: "תכנון לפי קטגוריה",
    category: "קטגוריה",
    originalPlan: "תכנון מקורי",
    currentPlan: "תכנון נוכחי",
    committed: "התחייבות",
    actual: "ביצוע",
    setPlan: "קביעת תכנון מקורי",
    adjustPlan: "עדכון תכנון",
    transfer: "העברה בין קטגוריות",
    transferFrom: "מקטגוריה",
    transferTo: "לקטגוריה",
    overrun: "חריגה",
    history: "היסטוריית שינויים",
    noSources: "עוד לא הוגדרו מקורות מימון",
    noCategories: "עוד לא הוגדרו קטגוריות - ניתן להוסיף בהגדרות",
    kindIncrease: "הגדלה",
    kindDecrease: "הקטנה",
    kindTransfer: "העברה",
  },
  expenses: {
    title: "הוצאות",
    subtitle: "כל הוצאה היא רשומה אחת לאורך כל חייה",
    newExpense: "הוצאה חדשה",
    description: "תיאור",
    supplier: "ספק",
    category: "קטגוריה",
    total: "סכום כולל מע\"מ (₪)",
    expenseDate: "תאריך הוצאה",
    deliveryDate: "תאריך אספקה / ביצוע",
    invoiceDate: "תאריך חשבונית",
    status: "סטטוס",
    payment: "תשלום",
    reference: "מס' הוצאה",
    empty: "אין הוצאות עדיין",
    emptyHint: "צרו את ההוצאה הראשונה",
    noResults: "אין תוצאות לסינון",
    filterQueue: "תור",
    queues: {
      awaiting_preapproval: "ממתין לאישור תקציבי מוקדם",
      sent_waiting_reference: "נשלח – ממתין לאסמכתא",
      authorized_not_fully_paid: "אושר – טרם שולם במלואו לספק",
      unfunded: "יתרה לא ממומנת",
      unpaid: "טרם שולם",
    },
    totalFiltered: "סה\"כ בסינון",
    open: "פתיחה",
  },
  expense: {
    back: "חזרה להוצאות",
    details: "פרטים",
    funding: "מימון",
    payments: "תשלומים לספק",
    party: "הגשה למממן",
    allocated: "ממומן",
    unfunded: "יתרה לא ממומנת – יש לבחור מקור מימון",
    paid: "שולם",
    outstanding: "יתרה לתשלום",
    addAllocation: "הוספת מקור מימון",
    source: "מקור מימון",
    removeAllocation: "הסרת מקור",
    transitions: {
      committed: "סימון כהתחייבות",
      incurred: "סימון כבוצע",
      closed: "סגירת הוצאה",
      cancelled: "ביטול הוצאה",
      reopen: "פתיחה מחדש",
    },
    closeBlocked: "לא ניתן לסגור את ההוצאה:",
    blockers: {
      FUNDING_NOT_RECONCILED: "סכומי המימון אינם תואמים לסכום ההוצאה",
      SUPPLIER_NOT_FULLY_PAID: "הספק טרם שולם במלואו",
      PARTY_PREAPPROVAL_MISSING: "חסר אישור תקציבי מוקדם",
      PARTY_REFERENCE_MISSING: "חסרה אסמכתא מהמפלגה",
      ALLOCATION_NOT_FULLY_PAID: "אחד ממקורות המימון טרם שולם במלואו",
      REQUIRED_DOCUMENTS_MISSING: "חסרים מסמכים נדרשים",
      ORDER_FORM_INCOMPLETE: "תהליך טופס ההזמנה לא הושלם",
    } as Record<string, string>,
    recordPayment: "רישום תשלום",
    paymentDate: "תאריך תשלום",
    confirmationSource: "מקור האישור",
    externalReference: "אסמכתא / מספר העברה",
    voidPayment: "ביטול תשלום",
    voided: "בוטל",
    noPayments: "לא נרשמו תשלומים",
    preapproval: "אישור תקציבי מוקדם",
    recordPreapproval: "רישום אישור תקציבי מוקדם",
    orderNumber: "מספר הזמנה",
    approvalCode: "קוד אישור",
    approverName: "שם המאשר",
    approvalDate: "תאריך אישור",
    preapprovedAmount: "סכום שאושר מראש (₪)",
    preapprovalExceeded: "סכום ההזמנה גבוה מהסכום שאושר מראש",
    markSent: "סימון כנשלח למממן",
    sentHint: "הסימון נעשה על ידך - המערכת אינה מאמתת מסירה ב־WhatsApp",
    markReturned: "הוחזר לתיקון",
    returnNote: "מה נדרש לתקן",
    recordReference: "רישום אסמכתא",
    referenceNumber: "מספר אסמכתא",
    authorizedAmount: "סכום מאושר (₪)",
    receivedDate: "תאריך קבלה",
    partialAuthorization: "המפלגה אישרה פחות מהמבוקש – יש לממן את היתרה ממקור אחר",
    requested: "סכום מבוקש",
    authorized: "סכום מאושר",
  },
  /** Budget Stage 5 - the party funding workflow. Four separate business
   * events, never one merged status. */
  party: {
    fundingSummary: "תמונת המימון",
    expenseTotal: "סכום ההוצאה",
    partyPreapproved: "אושר ע\"י המפלגה",
    partyFunding: "מימון מהמפלגה",
    donationFunding: "מימון מתרומות",
    personalFunding: "מימון עצמי",
    uncovered: "יתרה ללא מקור מימון",
    gapWarning: "חלק מסכום ההוצאה עדיין ללא מקור מימון - יש לבחור מקור מימון ליתרה (המערכת לא משייכת אותה אוטומטית)",
    gapNone: "כל סכום ההוצאה משויך למקורות מימון",
    allocationTitle: (name: string) => `מימון מפלגתי · ${name}`,
    preapprovalTitle: "אישור תקציבי מוקדם",
    preapprovalHint: "האישור ניתן לפני הפקת טופס ההזמנה הסופי ושליחתו לספק. אינו אסמכתת התשלום.",
    preapprovalNone: "טרם נרשם אישור תקציבי מוקדם",
    preapprovalCapHint: "הסכום שאושר מראש הוא תקרת המימון המפלגתי להוצאה. אם הוקצה יותר - יש להקטין את ההקצאה ולממן את היתרה ממקור אחר.",
    updatePreapproval: "עדכון אישור מוקדם",
    submissionTitle: "הגשה למממן",
    readiness: "מוכנות להגשה",
    readyOk: "כל התנאים להגשה מתקיימים",
    readyLapsed: "ההגשה סומנה כמוכנה, אך מאז השתנו הנתונים - יש לטפל בחסרים ולסמן שוב",
    missingDocuments: "מסמכים חסרים",
    markReady: "סימון כמוכן להגשה",
    markSent: "סימון כנשלח למממן",
    markReturned: "הוחזר לתיקון",
    returnNote: "מה נדרש לתקן",
    resendHint: "לאחר התיקון: עדכנו את הנדרש (כולל הפקת גרסה חדשה של טופס ההזמנה אם צריך), סמנו שוב כמוכן להגשה ושלחו מחדש.",
    attempts: "היסטוריית הגשות",
    noAttempts: "טרם בוצעה הגשה",
    attempt: (n: number) => `ניסיון ${n}`,
    events: { ready: "סומן כמוכן להגשה", sent: "נשלח למממן", returned: "הוחזר לתיקון" } as Record<string, string>,
    formVersion: (n: number) => `טופס הזמנה גרסה ${n}`,
    referenceTitle: "אסמכתת תשלום מהמפלגה",
    referenceHint: "האישור המאוחר של המפלגה לתשלום לספק. אינו מעיד שהספק שולם.",
    referenceNone: "טרם התקבלה אסמכתת תשלום",
    referenceNeedsSent: "ניתן לרשום אסמכתא לאחר סימון ההגשה כנשלחה",
    paymentsTitle: "תשלומי המפלגה לספק",
    paymentsHint: "המפלגה משלמת לספק ישירות - הכסף אינו עובר דרך קופת הקמפיין.",
    paymentsNeedReference: "ניתן לרשום תשלום מפלגתי לאחר קבלת אסמכתת תשלום",
    partyAllocation: "הקצאה מפלגתית",
    paidByParty: "שולם ע\"י המפלגה",
    remaining: "יתרה לתשלום",
    addPayment: "רישום תשלום מהמפלגה",
    history: "היסטוריה",
    noHistory: "אין שינויים",
    historyActions: { insert: "נרשם", update: "עודכן", delete: "נמחק", event: "אירוע" } as Record<string, string>,
    note: "הערות",
    recordedBy: "נרשם ע\"י",
    blockers: {
      PREAPPROVAL_REQUIRED: "חסר אישור תקציבי מוקדם",
      EXPENSE_NOT_SUBMITTABLE: "יש לסמן את ההוצאה כהתחייבות או כבוצע",
      EXPENSE_LOCKED: "ההוצאה סגורה או מבוטלת",
      PARTY_EXCEEDS_PREAPPROVAL: "המימון המפלגתי גבוה מהסכום שאושר מראש",
      ORDER_FORM_MISSING: "טרם הופק טופס הזמנה סופי",
      SUPPLIER_SIGNATURE_MISSING: "חסר טופס הזמנה חתום ע\"י הספק (לגרסה האחרונה)",
      REQUIRED_DOCUMENTS_MISSING: "חסרים מסמכים נדרשים",
      ORDER_FORM_OUTDATED: "נתוני ההוצאה השתנו מאז הפקת הטופס - יש להפיק גרסה חדשה",
    } as Record<string, string>,
    submissionBlocked: "לא ניתן להתקדם בהגשה:",
  },
  suppliers: {
    title: "ספקים",
    subtitle: "פרטי ספקים, יתרות ופרטי בנק מוגנים",
    newSupplier: "ספק חדש",
    businessName: "שם העסק",
    contactName: "איש קשר",
    phone: "טלפון (WhatsApp)",
    taxId: "ח.פ / ע.מ",
    address: "כתובת",
    expenseCount: "הוצאות",
    totalAmount: "סה\"כ",
    outstanding: "יתרה לתשלום",
    outstandingParty: "באחריות המפלגה",
    outstandingCampaign: "באחריות הקמפיין",
    outstandingUnfunded: "לא ממומן",
    empty: "אין ספקים",
    duplicateTaxId: "קיים כבר ספק עם מספר זה",
    bank: "פרטי בנק",
    bankMasked: "חשבון המסתיים ב־",
    bankNone: "לא הוזנו פרטי בנק",
    reveal: "הצגת פרטי בנק מלאים",
    changeBank: "עדכון פרטי בנק",
    bankCode: "קוד בנק",
    branchCode: "סניף",
    accountNumber: "מספר חשבון",
    accountHolder: "שם בעל החשבון",
    stepUpTitle: "אימות זהות",
    stepUpHint: "פעולה רגישה - יש להזין את הסיסמה שלך",
    password: "סיסמה",
    confirm: "אישור",
  },
  settings: {
    title: "הגדרות תקציב",
    subtitle: "קטגוריות, מקורות מימון, כללי מסמכים וספים",
    categories: "קטגוריות הוצאה",
    newCategory: "קטגוריה חדשה",
    categoryName: "שם הקטגוריה",
    moveUp: "העברה למעלה",
    moveDown: "העברה למטה",
    inUse: "בשימוש - ניתן להשבית בלבד",
    sources: "מקורות מימון",
    rules: "כללי מסמכים וספים",
    threshold: "סף (₪)",
    ruleAlways: "תמיד",
    ruleAbove: "כאשר הסכום מעל",
    ruleAboveOrEqual: "כאשר הסכום לפחות",
    ruleCategory: "בקטגוריות נבחרות",
    ruleManual: "לפי סימון בהוצאה",
    period: "תקופת תקציב",
    periodStart: "מתאריך",
    periodEnd: "עד תאריך",
    periodHint: "בלתי תלויה במועד הבחירות",
    orderForm: "ברירות מחדל לטופס ההזמנה",
    branchName: "שם הסניף",
    branchNumber: "מספר הסניף",
    defaultOrderer: "שם המזמין",
    electionYearLabel: "שנת הבחירות",
    whatsapp: "WhatsApp",
    funderPhone: "מספר המממן",
    alerts: "התראות (ימים)",
    alertMissingDocs: "מסמכים חסרים",
    alertSupplierForm: "טופס ספק לא הוחזר",
    alertNoReference: "ללא אסמכתא",
    alertUnpaid: "אושר ולא שולם",
    usageWarning: "אזהרת ניצול קטגוריה (%)",
    documentKinds: { party: "מפלגתי", donation: "תרומות", personal: "אישי", any: "כל המקורות" },
    thresholdHint: "ספים נבדקים כ\"מעל\": הוצאה של בדיוק 1,500 ₪ אינה מחייבת את המסמך",
    ruleCategories: "קטגוריות",
    chooseCategories: "בחירת קטגוריות",
    noCategoriesChosen: "לא נבחרו קטגוריות",
    documentTypes: "סוגי מסמכים",
    newDocumentType: "סוג מסמך חדש",
    documentTypeName: "שם סוג המסמך",
    systemType: "מערכת",
  },
  documents: {
    title: "מסמכים",
    checklist: "מסמכים נדרשים",
    snapshotNote: "ההוצאה סגורה - מוצגות הדרישות שחלו בעת הסגירה",
    ready: "כל המסמכים הנדרשים קיימים",
    notReady: "חסרים מסמכים נדרשים",
    noRequirements: "אין מסמכים נדרשים להוצאה זו - ניתן לצרף מסמכים לפי הצורך",
    required: "נדרש",
    optional: "רשות",
    notRequired: "לא נדרש",
    present: "קיים",
    missing: "חסר",
    always: "תמיד נדרש",
    above: (amount: string) => `הסכום מעל ${amount}`,
    atLeast: (amount: string) => `הסכום לפחות ${amount}`,
    notAbove: (amount: string) => `לא נדרש - הסכום אינו מעל ${amount}`,
    notAtLeast: (amount: string) => `לא נדרש - הסכום נמוך מ־${amount}`,
    inCategory: "נדרש בקטגוריה זו",
    notInCategory: "לא נדרש בקטגוריה זו",
    manualOn: "סומן כנדרש בהוצאה זו",
    manualOff: "ניתן לסמן כנדרש בהוצאה זו",
    fromSupplier: "מתיק הספק",
    fromReturn: "חתום ומוחזר",
    managed: "מנוהל בטופס ההזמנה",
    upload: "העלאת מסמך",
    uploadFor: "העלאה",
    replace: "גרסה חדשה",
    download: "הורדה",
    versions: "גרסאות",
    showVersions: "הצגת גרסאות קודמות",
    hideVersions: "הסתרת גרסאות קודמות",
    archive: "העברה לארכיון",
    restore: "שחזור מהארכיון",
    archived: "בארכיון",
    archiveReason: "סיבת ההעברה לארכיון",
    version: (n: number) => `גרסה ${n}`,
    current: "נוכחית",
    uploadTitle: "העלאת מסמך",
    replaceTitle: "העלאת גרסה חדשה",
    replaceHint: "הגרסה הקודמת נשמרת בהיסטוריה ואינה נמחקת",
    type: "סוג מסמך",
    file: "קובץ",
    fileHint: "PDF, JPG, PNG או HEIC - עד 10MB",
    heicHint: "קובץ HEIC נשמר כפי שהוא; ייתכן שהדפדפן לא יציג אותו, אך ניתן להוריד אותו",
    docTitle: "כותרת (רשות)",
    validUntil: "בתוקף עד (רשות)",
    validUntilShort: "בתוקף עד",
    expired: "פג תוקף",
    all: "כל המסמכים",
    none: "לא צורפו מסמכים",
    uploaded: "המסמך נשמר",
    archivedToast: "המסמך הועבר לארכיון",
    flag: (name: string) => `${name} נדרש להוצאה זו`,
    by: (name: string, date: string) => `${name} · ${date}`,
  },
  orderForm: {
    title: "טופס הזמנה",
    states: {
      not_applicable: "לא רלוונטי - אין מימון מפלגתי",
      draft: "טיוטה - ממתין לאישור תקציבי מוקדם",
      ready: "מוכן להפקה",
      generated: "הופק - טרם אושרה שליחה לספק",
      sent: "נשלח לספק - ממתין לטופס חתום",
      returned: "התקבל טופס חתום מהספק",
    } as Record<string, string>,
    signatureRequired: "נדרשת חתימת ספק (ההזמנה מעל הסף)",
    signatureNotRequired: "חתימת ספק אינה נדרשת - טופס חתום ע\"י הסניף מספיק",
    preview: "תצוגה מקדימה (טיוטה)",
    generate: "הפקת טופס סופי",
    regenerate: "הפקת גרסה חדשה",
    regenerateTitle: "הפקת גרסה חדשה של הטופס",
    regenerateHint: "הגרסה הקודמת נשמרת; טופס חתום קודם אינו תקף לגרסה החדשה",
    generated: "הטופס הופק ונשמר",
    blockers: {
      PREAPPROVAL_REQUIRED: "הטופס הסופי מופק רק לאחר רישום אישור תקציבי מוקדם",
      EXPENSE_INCOMPLETE: "יש להשלים ספק, קטגוריה, סכום ותאריך",
      EXPENSE_LOCKED: "ההוצאה סגורה או מבוטלת",
      ORDER_FORM_NOT_APPLICABLE: "טופס הזמנה נדרש רק להוצאה במימון מפלגתי",
    } as Record<string, string>,
    versions: "גרסאות הטופס",
    latest: "נוכחית",
    superseded: "הוחלפה",
    send: "שליחה לספק",
    sendTitle: "שליחת הטופס לספק",
    sendHint: "שלחו את הקובץ לספק ב־WhatsApp ואשרו כאן לאחר השליחה. המערכת אינה מאמתת מסירה.",
    share: "שיתוף הקובץ",
    downloadFile: "הורדת הקובץ",
    openWhatsapp: "פתיחת WhatsApp",
    confirmSent: "אישור: הטופס נשלח לספק",
    sentNote: "הערה (רשות)",
    sentBy: (name: string, date: string) => `נשלח ע"י ${name} · ${date}`,
    uploadReturn: "העלאת טופס חתום",
    returnTitle: "העלאת טופס חתום מהספק",
    returnHint: (n: number) => `הקובץ יקושר לגרסה ${n} של הטופס`,
    returns: "טפסים חתומים",
    whatsappText: (ref: number, version: number) => `שלום, מצורף טופס הזמנה (הוצאה ${ref}, גרסה ${version}). נא לחתום, להחתים ולהחזיר. תודה.`,
  },
  supplierFile: {
    open: "תיק ספק",
    documents: "מסמכי הספק",
    documentsHint: "אישור ניהול חשבון בתוקף משמש את כל הוצאות הספק",
    upload: "העלאת מסמך ספק",
    expenses: "הוצאות הספק",
    noExpenses: "אין הוצאות לספק זה",
    ready: "מסמכים מלאים",
    missing: (n: number) => `חסרים ${n} מסמכים`,
    openExpense: "פתיחת ההוצאה",
  },
  errors: {
    FORBIDDEN: "אין לך הרשאה לפעולה זו",
    MODULE_NOT_ENABLED: "ניהול התקציב אינו פעיל עבור מערכת זו",
    UNAUTHORIZED: "פג תוקף ההתחברות - יש להתחבר מחדש",
    STALE_VERSION: "הרשומה עודכנה בינתיים - הנתונים רועננו, נסו שוב",
    STEPUP_REQUIRED: "נדרש אימות זהות מחדש",
    RATE_LIMITED: "יותר מדי ניסיונות - נסו שוב מאוחר יותר",
    NOT_FOUND: "הרשומה לא נמצאה",
    INVALID_INPUT: "אחד השדות אינו תקין",
    DUPLICATE_NAME: "קיים כבר פריט בשם זה",
    DUPLICATE_TAX_ID: "קיים כבר ספק עם מספר זה",
    CATEGORY_IN_USE: "הקטגוריה בשימוש - ניתן להשבית בלבד",
    ORIGINAL_LOCKED: "הסכום המקורי נעול לאחר התאמה - יש לבצע התאמה",
    AMOUNT_BELOW_ZERO: "הסכום אינו יכול לרדת מתחת לאפס",
    INSUFFICIENT_PLAN: "אין די יתרת תכנון בקטגוריית המקור",
    SUPPLIER_INACTIVE: "הספק אינו פעיל",
    CATEGORY_INACTIVE: "הקטגוריה אינה פעילה",
    SOURCE_INACTIVE: "מקור המימון אינו פעיל",
    SOURCE_KIND_LOCKED: "לא ניתן לשנות סוג למקור שכבר בשימוש",
    EXPENSE_LOCKED: "ההוצאה סגורה או מבוטלת",
    EXPENSE_INCOMPLETE: "יש להשלים ספק, קטגוריה, סכום ותאריך",
    EXPENSE_NOT_PAYABLE: "ניתן לרשום תשלום רק בהתחייבות או בביצוע",
    EXPENSE_NOT_SUBMITTABLE: "יש לסמן את ההוצאה כהתחייבות לפני הגשה",
    INVALID_TRANSITION: "מעבר סטטוס לא חוקי",
    REASON_REQUIRED: "יש לציין סיבה",
    ALLOCATION_REQUIRED: "יש להגדיר לפחות מקור מימון אחד",
    TOTAL_REQUIRED: "יש להזין סכום להוצאה לפני הקצאת מימון",
    ALLOCATION_FROZEN: "המימון המפלגתי נעול בזמן הגשה או לאחר אסמכתא",
    ALLOCATION_HAS_PAYMENTS: "לא ניתן להסיר מקור שנרשמו עליו תשלומים",
    ALLOCATION_HAS_PARTY_WORKFLOW: "לא ניתן להסיר מקור מפלגתי שהחל בו תהליך",
    ALLOCATION_BELOW_PAID: "לא ניתן להקטין מתחת לסכום ששולם",
    ALLOCATIONS_EXCEED_TOTAL: "סכומי המימון עולים על סכום ההוצאה",
    TOTAL_BELOW_PAID: "סכום ההוצאה נמוך מהסכום ששולם",
    PAYMENTS_EXIST: "לא ניתן לבטל הוצאה עם תשלומים - יש לבטל את התשלומים תחילה",
    PAYMENT_EXCEEDS_ALLOCATION: "התשלום עולה על היתרה של מקור המימון",
    PAYMENT_ALREADY_VOIDED: "התשלום כבר בוטל",
    IDEMPOTENCY_CONFLICT: "התשלום כבר נרשם",
    PARTY_REFERENCE_REQUIRED: "תשלום מפלגתי אפשרי רק לאחר קבלת אסמכתא",
    NOT_A_PARTY_ALLOCATION: "הפעולה אפשרית רק למימון מפלגתי",
    PREAPPROVAL_REQUIRED: "יש לרשום אישור תקציבי מוקדם תחילה",
    PREAPPROVAL_LOCKED: "לא ניתן לשנות אישור מוקדם לאחר קבלת אסמכתא",
    SUBMISSION_NOT_SENT: "יש לסמן שליחה למממן לפני רישום אסמכתא",
    REFERENCE_LOCKED: "לא ניתן לשנות אסמכתא לאחר שנרשם תשלום",
    AUTHORIZED_EXCEEDS_REQUEST: "הסכום המאושר עולה על הסכום המבוקש",
    CLOSE_BLOCKED: "לא ניתן לסגור את ההוצאה",
    UNSUPPORTED_FILE_TYPE: "סוג הקובץ אינו נתמך - PDF, JPG, PNG או HEIC בלבד",
    FILE_TOO_LARGE: "הקובץ גדול מ־10MB",
    INVALID_FILE: "תוכן הקובץ אינו תואם לסוג הקובץ",
    TOO_MANY_PENDING_UPLOADS: "יותר מדי העלאות פתוחות - נסו שוב בעוד מספר דקות",
    UPLOAD_EXPIRED: "תוקף ההעלאה פג - נסו שוב",
    UPLOAD_MISSING: "הקובץ לא הגיע לשרת - נסו שוב",
    UPLOAD_FAILED: "העלאת הקובץ נכשלה - נסו שוב",
    STORAGE_ERROR: "שגיאת אחסון - נסו שוב",
    DOCUMENT_ARCHIVED: "המסמך בארכיון - יש לשחזר אותו תחילה",
    DOCUMENT_TYPE_MANAGED: "מסמך זה מנוהל בטופס ההזמנה",
    DOCUMENT_TYPE_SYSTEM: "לא ניתן לשנות סוג מסמך מערכתי",
    ORDER_FORM_NOT_APPLICABLE: "טופס הזמנה נדרש רק להוצאה במימון מפלגתי",
    ORDER_FORM_SUPERSEDED: "קיימת גרסה חדשה יותר של הטופס",
    SUBMISSION_BLOCKED: "לא ניתן להתקדם בהגשה - יש להשלים את החסר",
    SUBMISSION_NOT_READY: "יש לסמן את ההגשה כמוכנה לפני השליחה",
    PARTY_EXCEEDS_PREAPPROVAL: "המימון המפלגתי אינו יכול לעלות על הסכום שאושר מראש",
    NETWORK: "אין חיבור לאינטרנט - בדקו את החיבור ונסו שוב",
  } as Record<string, string>,
  genericError: "אירעה שגיאה - נסו שוב",
};

export function budgetErrorMessage(code: string | undefined): string {
  return (code && BUDGET_TEXT.errors[code]) || BUDGET_TEXT.genericError;
}
